class CreateTables < ActiveRecord::Migration[5.0]
  def change
    create_table "results", force: :cascade do |t|
      t.string   "MachineGuid"
      t.string   "Cleared"
      t.string   "DateTime"
      t.string   "Disqualified"
      t.string   "Grade"
      t.string   "Guid"
      t.string   "Held"
      t.string   "LetGo"
      t.string   "MissedHold"
      t.string   "LifeRemainingSeconds"
      t.string   "MaxCombo"
      t.string   "Modifiers"
      t.string   "Pad"
      t.string   "PercentDP"
      t.string   "PlayerGuid"
      t.string   "ProductID"
      t.string   "Air"
      t.string   "Chaos"
      t.string   "Fakes"
      t.string   "Freeze"
      t.string   "Hands"
      t.string   "Holds"
      t.string   "Jumps"
      t.string   "Lifts"
      t.string   "Mines"
      t.string   "Notes"
      t.string   "Rolls"
      t.string   "Stream"
      t.string   "TapsAndHolds"
      t.string   "Voltage"
      t.string   "Score"
      t.string   "StageGuid"
      t.string   "SurviveSeconds"
      t.string   "AvoidMine"
      t.string   "CheckpointHit"
      t.string   "CheckpointMiss"
      t.string   "HitMine"
      t.string   "Miss"
      t.string   "W1"
      t.string   "W2"
      t.string   "W3"
      t.string   "W4"
      t.string   "W5"
      t.string   "Dir"
      t.string   "Difficulty"
      t.string   "Level"
      t.string   "StepsType"
      t.string   "_id"
      t.string   "_index"
      t.string   "_score"
      t.string   "_type"
      t.datetime "created_at",           null: false
      t.datetime "updated_at",           null: false
    end
  end
end
